config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :recipes
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    
    redirect_to root_path
    #redirect_to home_index_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :image, :ingredients)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li>
      <h2><%= recipe.name %></h2>
      <p><%= recipe.ingredients %></p>
      <%= link_to 'Show', recipe_path(recipe) %>
      <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kz0527</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.label :ingredients %>
  <%= f.text_area :ingredients %>

  <%= f.submit "Create Recipe" %>
<% end %>

<%= link_to 'Back to Home', root_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<img src="<%= @recipe.image %>" alt="<%= @recipe.name %>">

<p><%= @recipe.ingredients %></p>

<%= link_to 'Back to Home', root_path %>